/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

import kotlinx.serialization.json.Json
import java.io.File
import kotlin.system.exitProcess

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun calculateSpellDPR(spell: Spell) {
//    println("")
//    println(Json.encodeToString(spell))
//    println("")

    // ----------------------------------------------------------------------------------------------------
    // CHARACTER TRAITS

    // fields to pull from character input ?
    var isLucky: Boolean = false            // halfling feature
    var isPlayerEvasive: Boolean = false    // optional feature for high-level Ranger, Rogue, Monk

    // ----------------------------------------------------------------------------------------------------
    // PRECONDITIONS

    // If the target has a bonus to their saving throw determined by a dice roll (such as from the Bless spell) then enter those dice here.
    var bonusDiceToSave = DiceBlock(0, 0, 0, 0, 0)

    // If the target has a penalty to their saving throw determined by a dice roll (such as by the Bane spell) then enter those dice here.
    var penaltyDiceToSave = DiceBlock(1, 0, 0, 0, 0)

    // ----------------------------------------------------------------------------------------------------
    // If you get a bonus on only one hit or target, such as with the Evoker's "Empowered Evocation" ability, you can enter the bonus here.
    // we may be able to extract this from spell properties ?
    var bonusDamage = 0
    var bonusDamageOnFirstHit = DiceBlock(0, 0, 0, 0, 0)

    var dpr = DamagePerRound(0, 18, isLucky)

    dpr.calculateSpellDPR (spell, bonusDamage, bonusDamageOnFirstHit, isPlayerEvasive, bonusDiceToSave, penaltyDiceToSave)
    println ("")
}

fun main(args : Array<String>) {
    val spells = ArrayList<Spell>()
    val spellNameArray = ArrayList<String>()

    // load spell books, and build the spell name
    for (arg in args) {
        if (! arg.endsWith(".json")) {
            spellNameArray.add(arg) // if not a filename, then it is part of the spell name
            continue
        }
        // val fileName = "/Users/dave/dnd/json/addendum.json"
        // val jsonString = File(fileName).readText()
        val jsonString = File(arg).readText()

        val current: List<Spell> = Json.decodeFromString(jsonString)
        spells.addAll (current)
    }

    if (! spellNameArray.isEmpty()) {
        val spellName = spellNameArray.joinToString(separator = " ")
        //println("spell name = " + spellName)

        for (spell in spells) {
            if (spell.name == spellName && spell.book == "Free Basic Rules (2024)") {
                calculateSpellDPR(spell)
            }
        }
        exitProcess(0)
    }

    // debug only: if no spell name given, iterate over spells, and print "data records"
    for (spell in spells) {
        if (spell.properties.dataDatarecords != null) {
            val dlist: List<DataRecord> = Json.decodeFromString(spell.properties.dataDatarecords)
            // println(dlist)
            for (d in dlist) {
                println(d)
                val payload: DataRecordPayload = Json.decodeFromString(d.payload)
                println(payload)
            }
        }
    }
}
