/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

import com.vikinghelmet.dnd.dpr.character.Character
import com.vikinghelmet.dnd.dpr.turn.Attack
import com.vikinghelmet.dnd.dpr.turn.AttackResultFormatter
import com.vikinghelmet.dnd.dpr.turn.Turn
import com.vikinghelmet.dnd.dpr.turn.TurnCalculator
import com.vikinghelmet.dnd.dpr.turn.TurnCalculator.character
import com.vikinghelmet.dnd.dpr.turn.TurnCalculator.monsters
import com.vikinghelmet.dnd.dpr.turn.TurnCalculator.spells
import com.vikinghelmet.dnd.dpr.turn.TurnCalculator.turns
import com.vikinghelmet.dnd.dpr.util.Globals
import kotlinx.serialization.json.Json
import okhttp3.OkHttpClient
import okhttp3.Request
import java.io.File
import java.io.IOException
import java.io.InputStream

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun getRequest(url: String): String? {
    val client = OkHttpClient() // TODO move?
    val request = Request.Builder().url(url).build()

    val response = client.newCall(request).execute()
    if (response.code >= 400) {
        throw IOException("request failed, response code = "+response.code)
    }
    return response.body?.string() ?: "{}"
}

fun getFileOrURL(fileOrUrl: String): String? {
    return if (fileOrUrl.startsWith("http")) {
        getRequest(fileOrUrl)
    }
    else {
        File(fileOrUrl).readText()
    }
}

fun getCharacter(arg: String): Character? {
    if (!arg.contains(":")) return null
    val id = arg.split(":")[1]
    val charJson = getFileOrURL("https://character-service.dndbeyond.com/character/v5/character/"+id) ?: "{}"
    //println ("charJson = "+charJson)
    return Json.decodeFromString(charJson)
}

fun getResource(fileName: String): String? {
    val inputStream: InputStream = object {}.javaClass.getResourceAsStream("/$fileName") ?: return null
    try {
        return inputStream.bufferedReader().use { it.readText() }
    } catch (e: Exception) {
        e.printStackTrace()
        return null
    }
}

fun spellTest() {
    for (spell in spells) {
        if (spell.is2014()) continue // TODO ???

        val effect = spell.getTargetEffect()
        if (!effect.isEmpty()) {
            println(String.format("%-30s %-20s %s", spell.name, spell.getSpellFailConditions(), effect))
        }
    }
}

fun showUsage() {
    System.err.println("""
Usage:  [-d] [--csv]  [file.json ...]  [character]  < dump[:opt] | search<opt> | <attacks> | turns >

Options:

    -d      debug
    --csv   CSV output

File:

     file.json   load spell or monster data; this is optional: program contains most 2014 and 2024 data

Character:

     NumericID   read character from DND Beyond API (character must have public visibility)
     file.json   read character from a local file

Dump:

     dump:spells     export all known spells
     dump:monsters   export all known monsters
     dump:attacks    export attacks from user input
     dump:character  export (minimal) character data from DND Beyond
     dump            export all of the above

Search:

     search:spells:NAME      search for name in list of spells, and display details if found
     search:monsters:NAME    search for name in list of spells, and display details if found

Attacks:

     -a  <monster spellOrWeapon> ...    (multiple pairs allowed)

Turns:

     an array of turns, each with an array of attacks, for example:

         [ { "attacks": [ { "monster": "Goblin", "attack": "Longbow" } ] } ]


     optional notes and preconditions are also supported, for example:

    [
      {
        "notes": [
            "Assume Mind Sliver and HM were cast prior to this turn (following 2024 rules):",
            "- MS adds a 1d4 penalty to the target's next saving throw",
            "- HM adds 1d6 to each subsequent attack roll for 1 hour (including melee/range attacks)"
        ],
        "preconditions": {
            "bonusDiceToSave":   { "d4": 0, "d6": 0, "d8": 0, "d10": 0, "d12": 0 },
            "penaltyDiceToSave": { "d4": 1, "d6": 0, "d8": 0, "d10": 0, "d12": 0 },
            "bonusDamageDice":   { "d4": 0, "d6": 1, "d8": 0, "d10": 0, "d12": 0 },
            "bonusDamage": 0
        },
    
        "attacks": [
            { "monster": "Goblin", "attack": "Longbow" },
            { "monster": "Goblin", "attack": "Hail of Thorns", "isBonusAction": true, "numTargets": 3 }
        ]    
      } 
    ]            
""")

}

fun main(args : Array<String>) {
    var exitEarly = false

    if (args.isEmpty()) {
        showUsage()
        System.exit(0)
    }

    for (filename in mutableListOf("spells.json","extra.spells.json")) {
        spells.addAll (Json.decodeFromString (getResource(filename) ?: "[]"))
    }

    monsters.addAll (Json.decodeFromString (getResource("monsters.json") ?: "[]"))

    // each arg should be a json file (spells, monsters, character, or attacks) or a debug cmd (dump, search, test)
    for (i in args.indices) {
        val arg = args[i]
        if (arg.startsWith("-")) {
            when (arg) {
                "-d" -> Globals.debug = true
                "--csv" -> AttackResultFormatter.isCSV = true;
                "-a" -> {
                    val attackList = mutableListOf<Attack>()
                    for (j in (i+1) until args.size step 2) {
                        val monsterName = args[j]
                        val attackName = args[j+1]
                        attackList.add(Attack(monsterName, attackName))
                    }
                    turns.add(Turn(null, attackList, null))
                    break
                }
                else -> println("invalid argument: $arg")
            }
        }
        else if (arg.endsWith(".json")) {
            val jsonString = getFileOrURL(arg)
            if (jsonString == null) {
                println("unable to read input: $arg")
            }
            else if (jsonString.contains("School")) {
                spells.addAll(Json.decodeFromString(jsonString))
            }
            else if (jsonString.contains("\"Monsters\"")){
                monsters.addAll(Json.decodeFromString(jsonString))
            }
            else if (jsonString.contains("\"monster\"")) {
                turns.addAll(Json.decodeFromString(jsonString))
                AttackResultFormatter.scenario = File(arg).nameWithoutExtension
            }
            else if (jsonString.contains("\"username\"")) {
                character = Json.decodeFromString(jsonString)
            }
        }
        else if (arg.endsWith(".json")){
            println("unknown file type: $arg")
        }
        else if (arg.startsWith("character")) {
            character = getCharacter(arg)
        }
        else if (arg.startsWith("dump")) {
            TurnCalculator.dump(arg)
            exitEarly = true
        }
        else if (arg.startsWith("search")) {
            TurnCalculator.search(arg)
            exitEarly = true
        }
        else if (arg.startsWith("test")) {
            character?.test()
            exitEarly = true
        }
        else if (arg.startsWith("spellTest")) {
            spellTest()
            exitEarly = true
        }
    }

    if (exitEarly) {
        // quietly go away
    }
    else if (spells.isEmpty()) {
        println("no spell data")
    }
    else if (monsters.isEmpty()) {
        println("no monsters data")
    }
    else if (character == null) {
        println("no character data")
    }
    else if (turns.isEmpty()) {
        println("no attacks specified")
    }
    else {
        TurnCalculator.calculateDPRForAllTurns()
    }
}
