/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

import com.vikinghelmet.dnd.dpr.action.Attack
import com.vikinghelmet.dnd.dpr.action.AttackResultFormatter
import com.vikinghelmet.dnd.dpr.action.Combatant
import com.vikinghelmet.dnd.dpr.action.Turn
import com.vikinghelmet.dnd.dpr.character.PlayerCharacter
import com.vikinghelmet.dnd.dpr.editable.EditableFields
import com.vikinghelmet.dnd.dpr.editable.EditablePlayerCharacter
import com.vikinghelmet.dnd.dpr.scenario.combat.Combat
import com.vikinghelmet.dnd.dpr.scenario.onesided.*
import com.vikinghelmet.dnd.dpr.util.CharacterAPI
import com.vikinghelmet.dnd.dpr.util.CharacterAPI.getCharacterApiURL
import com.vikinghelmet.dnd.dpr.util.Constants
import com.vikinghelmet.dnd.dpr.util.Constants.DEFAULT_NUM_TARGETS
import com.vikinghelmet.dnd.dpr.util.Constants.DEFAULT_TARGET_SPACING
import com.vikinghelmet.dnd.dpr.util.Constants.NUM_TURNS_PER_SCENARIO
import com.vikinghelmet.dnd.dpr.util.DprFiles
import com.vikinghelmet.dnd.dpr.util.Globals
import dev.shivathapaa.logger.api.LogLevel
import dev.shivathapaa.logger.api.LoggerFactory
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.Json
import java.io.File
import java.io.InputStream
import java.util.*


class DprCmd {
    val greeting: String
        get() {
            return "Hello World!"
        }

    init {
        Globals.initLogger(LogLevel.WARN)
    }
}

val logger = LoggerFactory.get(DprCmd::class.simpleName ?: "no simpleName")   // DprCmd

val dprFiles = DprFiles(System.getProperty("user.home"))

fun getFileOrURL(fileOrUrl: String): String? {
    return if (fileOrUrl.startsWith("http")) {
        var body = ""
        runBlocking {
            body = CharacterAPI.getRequest(fileOrUrl)
        }
        body
    }
    else {
        File(fileOrUrl).readText()
    }
}

fun getCombatantGroup(combatantName: String): List<Combatant> {
    val result: MutableList<Combatant> = mutableListOf()

    if (combatantName.startsWith("party:")) {
        val level = combatantName.split(":".toRegex())[1].toInt()

        dprFiles.getEditableCharacterList().forEach { name ->
            val c = dprFiles.getEditableCharacter(name)
            c!!.editableFields.level = level
            result.add(c)
        }
        return result
    }

    try {
        val monster = Globals.getMonster(combatantName)
        result.add(monster)
        return result
    }
    catch (e: Exception) {
        // if not a monster, combatant must be a player character
    }

    var playerCharacter: PlayerCharacter? = null
    if (combatantName.endsWith(".json") || combatantName.contains("/")) {
        val jsonString = getFileOrURL(combatantName)
        if (jsonString == null) {
            println("unable to read input: $combatantName")
        }
        else if (jsonString.contains("\"remoteId\"")) {
            playerCharacter = getEditableCharacter(jsonString)
            logger.debug { "# loaded editable character: $playerCharacter" }
        }
        else if (jsonString.contains("\"username\"")) {
            playerCharacter = Json.decodeFromString(jsonString)
        }
        else {
            logger.error { "unsupported json file: $combatantName" }
        }
    }
    else if (combatantName.startsWith("character")) {
        var remoteId: String? = CharacterAPI.getCharacterId(combatantName)
        if (remoteId != null) {
            playerCharacter = getCharacter(remoteId)
        }
    }

    if (playerCharacter != null) {
        result.add(playerCharacter)
    }
    return result
}

fun getCharacter(arg: String): com.vikinghelmet.dnd.dpr.character.PlayerCharacter? {
    var playerCharacter: com.vikinghelmet.dnd.dpr.character.PlayerCharacter? = null
    runBlocking {
        playerCharacter = CharacterAPI.getRemoteCharacterByUrl (getCharacterApiURL (arg)!!).second
    }
    return playerCharacter
}


fun getEditableCharacter(json: String): EditablePlayerCharacter? {
    if (json.isEmpty()) return null
    val editableFields: EditableFields = Json.Default.decodeFromString(json)

    val baseline = getCharacter(editableFields.remoteId) ?: return null
    return EditablePlayerCharacter(baseline, editableFields)
}

fun getResource(fileName: String): String? {
    val inputStream: InputStream = object {}.javaClass.getResourceAsStream("/$fileName") ?: return null
    try {
        return inputStream.bufferedReader().use { it.readText() }
    } catch (e: Exception) {
        e.printStackTrace()
        return null
    }
}

fun getProperties(fileName: String): java.util.Properties {
    val properties = Properties()
    val inputStream = object {}.javaClass.getResourceAsStream("/$fileName") ?: return properties
    inputStream.use { properties.load(it) }
    return properties
}

fun showResults(resultList: List<ScenarioResult>) {

    val sortedResults = ScenarioResult.topResults(resultList, Constants.SCENARIO_OUTPUT_MAX)

    // result summaries, prefixed with "#"
    val buf = StringBuilder()
    sortedResults.forEach {
        buf.append("# ")
            .append(Globals.getPercent(it.totalDamage))
            .append(" \t")
            .append(it.scenario.getLabel())
            .append("\n")
    }
    logger.warn { buf.toString() }

    // full results
    sortedResults.forEach {
        println(it.output())
    }
}

fun runScenarios(attacker: Combatant, target: Combatant, args : Array<String>, i: Int): List<ScenarioResult>
{
    val builder = ScenarioBuilder(attacker, target)
    val proximity = args[i].toInt() // required arg

    fun optionalArg(index: Int, default: Int) = if (index < args.size) args[index].toInt() else default

    val iterator = ScenarioIterator(
        builder.build(
            proximity,
            optionalArg(i + 1, NUM_TURNS_PER_SCENARIO),
            optionalArg(i + 2, DEFAULT_NUM_TARGETS),
            optionalArg(i + 3, DEFAULT_TARGET_SPACING)
        )
    )

    val resultList: MutableList<ScenarioResult> = mutableListOf()
    iterator.forEach { resultList.add(ScenarioCalculator(it).calculateDPRForAllTurns()) }
    return resultList
}

fun runCustomAttack(attacker: Combatant, target: Combatant, turnString: String) {
    val turns = ArrayList<Turn>()

    for (turn in turnString.split(";")) {
        val attackList = mutableListOf<Attack>()
        for (attackName in turn.split(",")) {
            try {
                val weapon = attacker.getWeaponList().firstOrNull { it.name == attackName }
                attackList.add(Attack(target, weapon!!))
            } catch (e: Exception) {
                val spell = Globals.getSpell(attackName, attacker.is2014())
                logger.verbose { "spell = ${spell.fullString()}" }
                attackList.add(Attack(target, Globals.getSpell(attackName, attacker.is2014())))
            }
        }
        turns.add(Turn(attackList))
    }

    if (turns.isEmpty()) {
        return
    }

    val attackNames = turns.map { it.attacks.map { it.action.toString() } }
    logger.debug { "attackNames = $attackNames" }

    val scenario = Scenario(attacker, turns, DEFAULT_NUM_TARGETS, DEFAULT_TARGET_SPACING)
    val scenarioResult = ScenarioCalculator(scenario).calculateDPRForAllTurns()

    scenarioResult.attackResults.forEach {
        logger.debug { "scenario result = ${it}" }
    }

    println(scenarioResult.output())
}

fun showUsage() {
    println("""
Usage:  [-d] [--csv]  <attacker>  <target>  <auto | attacks> 

Options:

    -i, -d          info/debug logging (default = warn)
    --csv           CSV output

Attacker/Target - any of the following:

     monsterName    read monster from application resources
     NumericID      read character from DND Beyond API (character must have public visibility)
     file.json      read character from a local file
     "party:N"      read all characters stored in application data directory, and set each character level to N

Auto:

     Automated bi-directional combat.  Participants choose their preferred actions based on expected DPR
      
Attacks:

     <turn[;turn...] >   

       - one/more turns (separated by semi-colon); each turn is a comma-separated list of spell or weapon name
       
OR
     <proximityInFeet>  [numTurns (${NUM_TURNS_PER_SCENARIO})]  [numTargets (${DEFAULT_NUM_TARGETS})]  [targetSpacing (${DEFAULT_TARGET_SPACING})]   

       - identify all possible attack scenarios for given conditions, compute DPR, and present the top 30 results

""")
}

fun main(args : Array<String>) {
    JulConfigurator()

    if (args.isEmpty()) {
        showUsage()
        System.exit(0)
    }

    Globals.initLogger(if (args.contains("-v")) LogLevel.VERBOSE
                else if (args.contains("-d")) LogLevel.DEBUG
                else if (args.contains("-i")) LogLevel.INFO
                else LogLevel.WARN)

    for (filename in mutableListOf("spells.json","extra.spells.json")) {
        Globals.addSpells(getResource(filename) ?: "[]")
    }

    Globals.addSubclassSpellsPrepared(getResource("subclass.spellprep.json") ?: "[]")

    Globals.addMonsters(getResource("monsters.json") ?: "[]")

    logger.debug { "All spell and monster resources loaded from" }

    var i=0
    args.forEach { arg ->
        when (arg) {
            "--csv" -> { AttackResultFormatter.isCSV = true; i++}
            "-i"    -> { Globals.initLogger(LogLevel.INFO); i++ }
            "-d"    -> { Globals.initLogger(LogLevel.DEBUG); i++ }
        }
    }

    if (args.size < i+3) {
        showUsage()
        System.exit(0)
    }

    val attackers = getCombatantGroup(args[i++])
    val targets   = getCombatantGroup(args[i++])

    if (args[i] == "auto") {
        Combat(attackers, targets).run()
    }
    else if (args[i].toIntOrNull() == null) {
        runCustomAttack (attackers[0], targets[0], args[i]) // proximity not specified: custom turns, single combat
    }
    else {
        logger.warn { "attackers = ${attackers.size}" }
        logger.warn { "targets   = ${targets.size}" }
        val resultList: MutableList<ScenarioResult> = mutableListOf()
        for (attacker in attackers) {
            for (target in targets) {
                resultList.addAll(runScenarios(attacker, target, args, i))
            }
        }
        showResults(resultList)
    }

    CharacterAPI.closeHttpClient() // don't forget to do this, otherwise the program may run forever
}

