/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

import com.vikinghelmet.dnd.dpr.scenario.Scenario
import com.vikinghelmet.dnd.dpr.scenario.ScenarioBuilder
import com.vikinghelmet.dnd.dpr.scenario.ScenarioCalculator
import com.vikinghelmet.dnd.dpr.turn.Attack
import com.vikinghelmet.dnd.dpr.turn.AttackResultFormatter
import com.vikinghelmet.dnd.dpr.turn.Turn
import com.vikinghelmet.dnd.dpr.util.Globals
import com.vikinghelmet.dnd.dpr.util.Globals.monsters
import com.vikinghelmet.dnd.dpr.util.Globals.spells
import com.vikinghelmet.dnd.dpr.util.Constants
import kotlinx.serialization.json.Json
import okhttp3.OkHttpClient
import okhttp3.Request
import java.io.File
import java.io.IOException
import java.io.InputStream

class DprCmd {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun prettyPrintCharacter(character: com.vikinghelmet.dnd.dpr.character.Character) {
    println ("")
    println (String.format("%-15s %-5s %s\n", "ability", "base", "withBonusesAdded"))

    for (ability in _root_ide_package_.com.vikinghelmet.dnd.dpr.character.stats.AbilityType.entries) {
        if (ability == _root_ide_package_.com.vikinghelmet.dnd.dpr.character.stats.AbilityType.ALL) continue
        val base = character.getRawAbilityScore(ability)
        val withBonuses = character.getModifiedAbilityScore(ability)
        //println ("$ability: base=$base, withBonuses=$mod")
        println (String.format("  %-15s %3d %8d", ability, base, withBonuses))
    }

    character.test() // remainder of that method is portable, does not use String.format
}

fun getRequest(url: String): String? {
    val client = OkHttpClient() // TODO move?
    val request = Request.Builder().url(url).build()

    val response = client.newCall(request).execute()
    if (response.code >= 400) {
        throw IOException("request failed, response code = "+response.code)
    }
    return response.body?.string() ?: "{}"
}

fun getFileOrURL(fileOrUrl: String): String? {
    return if (fileOrUrl.startsWith("http")) {
        getRequest(fileOrUrl)
    }
    else {
        File(fileOrUrl).readText()
    }
}

fun getCharacter(arg: String): com.vikinghelmet.dnd.dpr.character.Character? {
    if (!arg.contains(":")) return null
    val id = arg.split(":")[1]
    val charJson = getFileOrURL("https://character-service.dndbeyond.com/character/v5/character/"+id) ?: "{}"
    //println ("charJson = "+charJson)
    return Json.decodeFromString(charJson)
}

fun getResource(fileName: String): String? {
    val inputStream: InputStream = object {}.javaClass.getResourceAsStream("/$fileName") ?: return null
    try {
        return inputStream.bufferedReader().use { it.readText() }
    } catch (e: Exception) {
        e.printStackTrace()
        return null
    }
}


fun showUsage() {
    println("""
Usage:  [-d] [--csv] [+feat=name] [+aaa=N]  [file.json ...]  [character]  < dump[:opt] | search<opt> | <attacks> >

Options:

    -d              debug logging
    --csv           CSV output
    
    --maxTurns=N    number of turns per scenario (default = 5)
    --maxResults=N  number of results in final output (default = 30), sorted by totalDamage (see -z below)
    
    +feat=name      add feat
    +aaa=N          increase ability (3-letter shorthand = str, dex, ...) by N = [1-9]

File:

     file.json   load spell or monster data; this is optional: program contains most 2014 and 2024 data

Character:

     NumericID   read character from DND Beyond API (character must have public visibility)
     file.json   read character from a local file

Dump:

     dump:spells     export all known spells
     dump:monsters   export all known monsters
     dump:attacks    export attacks from user input
     dump:character  export (minimal) character data from DND Beyond
     dump:features   export supported features: racialTraits, actionModifiers, feats
     dump            export all of the above

Search:

     search:NAME     search for NAME in list of spells/monsters, and display details if found

Attacks:

     -a  <monster turn[;turn...] >          one/more turns, each a comma-separated list of spell or weapon name
     -z  <monster <"melee" or "range">>     run all possible 5-turn scenarios, then sort by total damage
  
""")

     println("test dprlib = "+ Constants)
}

fun main(args : Array<String>) {
    var exitEarly = false
    var character: com.vikinghelmet.dnd.dpr.character.Character? = null
    val turns = ArrayList<Turn>()

    if (args.isEmpty()) {
        showUsage()
        System.exit(0)
    }

    for (filename in mutableListOf("spells.json","extra.spells.json")) {
        spells.addAll (Json.decodeFromString (getResource(filename) ?: "[]"))
    }

    monsters.addAll (Json.decodeFromString (getResource("monsters.json") ?: "[]"))

    // each arg should be a json file (spells, monsters, character, or attacks) or a debug cmd (dump, search, test)
    for (i in args.indices) {
        val arg = args[i]
        if (arg.startsWith("+feat")) {
            val split = arg.split("=")
            character!!.addFeat(_root_ide_package_.com.vikinghelmet.dnd.dpr.character.feats.Feat.valueOf(split[1]))
        }
        else if (arg.startsWith("+")) {
            val split = arg.substringAfter("+").split("=")
            val ability = _root_ide_package_.com.vikinghelmet.dnd.dpr.character.stats.AbilityType.fromShortName(split[0]) ?: throw IllegalArgumentException("unknown ability: "+split[0])
            character!!.updateAbilityScore(ability, split[1].toInt())
        }
        else if (arg.startsWith("--maxTurns")) {
            Constants.NUM_TURNS_PER_SCENARIO = arg.split("=")[1].toInt()
        }
        else if (arg.startsWith("--maxResults")) {
            Constants.SCENARIO_OUTPUT_MAX = arg.split("=")[1].toInt()
        }
        else if (arg.startsWith("-")) {
            when (arg) {
                "-d" -> Globals.debug = true
                "--csv" -> AttackResultFormatter.isCSV = true;
                "-a" -> {
                    val monster = Globals.getMonster(args[i+1])

                    for (turn in args[i+2].split(";")) {
                        val attackList = mutableListOf<Attack>()
                        for (attackName in turn.split(",")) {
                            try {
                                attackList.add (Attack (monster, character!!.getWeapon(attackName)))
                            }
                            catch (e: Exception) {
                                attackList.add (Attack (monster, Globals.getSpell(attackName, character!!.is2014())))
                            }
                        }
                        turns.add(Turn(attackList))
                    }

                    break
                }
                "-z" -> {
                    val monster = Globals.getMonster(args[i+1])
                    val meleeOrRange = args[i+2]
                    ScenarioBuilder(character!!,monster).runScenarios (meleeOrRange.equals("melee"))
                }
                else -> println("invalid argument: $arg")
            }
        }
        else if (arg.endsWith(".json")) {
            val jsonString = getFileOrURL(arg)
            if (jsonString == null) {
                println("unable to read input: $arg")
            }
            else if (jsonString.contains("School")) {
                spells.addAll(Json.decodeFromString(jsonString))
            }
            else if (jsonString.contains("\"Monsters\"")){
                monsters.addAll(Json.decodeFromString(jsonString))
            }
            else if (jsonString.contains("\"username\"")) {
                character = Json.decodeFromString(jsonString)
            }
        }
        else if (arg.endsWith(".json")){
            println("unknown file type: $arg")
        }
        else if (arg.startsWith("character")) {
            character = getCharacter(arg)
        }
        else if (arg.startsWith("dump")) {
            Globals.dump(arg, character, turns)
            exitEarly = true
        }
        else if (arg.startsWith("search")) {
            Globals.search(arg)
            exitEarly = true
        }
        else if (arg.startsWith("test:character")) {
            prettyPrintCharacter(character!!)
            exitEarly = true
        }
        else if (arg.startsWith("test:available")) {
            ScenarioBuilder(character!!, Globals.getMonster("Goblin")).testActionsAvailable() // hack
            exitEarly = true
        }
    }

    if (exitEarly) {
        // quietly go away
    }
    else if (spells.isEmpty()) {
        println("no spell data")
    }
    else if (monsters.isEmpty()) {
        println("no monsters data")
    }
    else if (character == null) {
        println("no character data")
    }
    else if (turns.isNotEmpty()) {
        val scenario = Scenario(character, turns)
        val scenarioResult = ScenarioCalculator(scenario).calculateDPRForAllTurns()
        scenarioResult.output()
    }
}
