/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

import com.vikinghelmet.dnd.dpr.scenario.Scenario
import com.vikinghelmet.dnd.dpr.scenario.ScenarioBuilder
import com.vikinghelmet.dnd.dpr.scenario.ScenarioCalculator
import com.vikinghelmet.dnd.dpr.turn.Attack
import com.vikinghelmet.dnd.dpr.turn.AttackResultFormatter
import com.vikinghelmet.dnd.dpr.turn.Turn
import com.vikinghelmet.dnd.dpr.util.Constants
import com.vikinghelmet.dnd.dpr.util.Globals
import com.vikinghelmet.dnd.dpr.util.Globals.monsters
import com.vikinghelmet.dnd.dpr.util.Globals.spells
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.Json
import java.io.File
import java.io.InputStream

class DprCmd {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun prettyPrintCharacter(character: com.vikinghelmet.dnd.dpr.character.Character) {
    character.prettyPrintCharacter()
    /*
    println ("")

//    println (String.format("%-15s %-5s %s\n", "ability", "base", "withBonusesAdded"))
    println (StringBuffer()
        .append(Globals.rightPad("ability",15)).append(" ")
        .append(Globals.rightPad("base",5)).append(" ")
        .append(" withBonusesAdded").toString())

    for (ability in com.vikinghelmet.dnd.dpr.character.stats.AbilityType.entries) {
        if (ability == com.vikinghelmet.dnd.dpr.character.stats.AbilityType.ALL) continue
        val base = character.getRawAbilityScore(ability)
        val withBonuses = character.getModifiedAbilityScore(ability)
        //println ("$ability: base=$base, withBonuses=$mod")

        // println (String.format("  %-15s %3d %8d", ability, base, withBonuses))
        println (StringBuffer("  ")
            .append(Globals.rightPad("$ability",15)).append(" ")
            .append(Globals.rightPad("$base",5)).append(" ")
            .append(" $withBonuses").toString())
    }

    character.test() // remainder of that method is portable, does not use String.format

     */
}

fun getRequest(url: String): String? {
    /*
    val client = OkHttpClient() // TODO move?
    val request = Request.Builder().url(url).build()

    val response = client.newCall(request).execute()
    if (response.code >= 400) {
        throw IOException("request failed, response code = "+response.code)
    }
    return response.body?.string() ?: "{}"
     */
    var responseBody = ""

    runBlocking { // This makes the main thread block until the coroutine finishes
        responseBody = CmdTest.getRequest(url)
    }

    return responseBody
}

fun getFileOrURL(fileOrUrl: String): String? {
    return if (fileOrUrl.startsWith("http")) {
        var body = ""
        runBlocking {
            body = CmdTest.getRequest(fileOrUrl)
        }
        //getRequest(fileOrUrl)
        body
    }
    else {
        File(fileOrUrl).readText()
    }
}

fun getCharacter(arg: String): com.vikinghelmet.dnd.dpr.character.Character? {
    /*
    // extract ID from either a dndbeyond char url (.../ID), or simply "character:ID"
    val id = if (arg.contains("/")) arg.substringAfter("/characters/")
            else if (arg.contains(":")) arg.split(":")[1] else return null

    val charJson = getFileOrURL("https://character-service.dndbeyond.com/character/v5/character/"+id) ?: "{}"

    debug("getCharacter json length = "+ charJson.length)

    //println ("charJson = "+charJson)
    return Json.decodeFromString(charJson)

     */
    var character: com.vikinghelmet.dnd.dpr.character.Character? = null
    runBlocking {
        character = CmdTest.getCharacter(arg)
    }
    //getRequest(fileOrUrl)
    return character
}

fun getResource(fileName: String): String? {
    val inputStream: InputStream = object {}.javaClass.getResourceAsStream("/$fileName") ?: return null
    try {
        return inputStream.bufferedReader().use { it.readText() }
    } catch (e: Exception) {
        e.printStackTrace()
        return null
    }
}


fun showUsage() {
    println("""
Usage:  [-d] [--csv] [+feat=name] [+aaa=N]  [file.json ...]  [character]  < dump[:opt] | search<opt> | <attacks> >

Options:

    -d              debug logging
    --csv           CSV output
    
    --maxTurns=N    number of turns per scenario (default = 5)
    --maxResults=N  number of results in final output (default = 30), sorted by totalDamage (see -z below)
    
    +feat=name      add feat
    +aaa=N          increase ability (3-letter shorthand = str, dex, ...) by N = [1-9]

File:

     file.json   load spell or monster data; this is optional: program contains most 2014 and 2024 data

Character:

     NumericID   read character from DND Beyond API (character must have public visibility)
     file.json   read character from a local file

Dump:

     dump:spells     export all known spells
     dump:monsters   export all known monsters
     dump:attacks    export attacks from user input
     dump:character  export (minimal) character data from DND Beyond
     dump:features   export supported features: racialTraits, actionModifiers, feats
     dump            export all of the above

Search:

     search:NAME     search for NAME in list of spells/monsters, and display details if found

Attacks:

     -a  <monster turn[;turn...] >          one/more turns, each a comma-separated list of spell or weapon name
     -z  <monster <"melee" or "range">>     run all possible 5-turn scenarios, then sort by total damage
  
""")

     println("test dprlib = "+ Constants)
}

fun main(args : Array<String>) {
    var exitEarly = false
    var character: com.vikinghelmet.dnd.dpr.character.Character? = null
    val turns = ArrayList<Turn>()

    if (args.isEmpty()) {
        showUsage()
        System.exit(0)
    }

    for (filename in mutableListOf("spells.json","extra.spells.json")) {
        Globals.addSpells(getResource(filename) ?: "[]")
    }

    Globals.addMonsters(getResource("monsters.json") ?: "[]")

    // each arg should be a json file (spells, monsters, character, or attacks) or a debug cmd (dump, search, test)
    for (i in args.indices) {
        val arg = args[i]
        if (arg.startsWith("+feat")) {
            val split = arg.split("=")
            character!!.addFeat(com.vikinghelmet.dnd.dpr.character.feats.Feat.valueOf(split[1]))
        }
        else if (arg.startsWith("+")) {
            val split = arg.substringAfter("+").split("=")
            val ability = com.vikinghelmet.dnd.dpr.character.stats.AbilityType.fromShortName(split[0]) ?: throw IllegalArgumentException("unknown ability: "+split[0])
            character!!.updateAbilityScore(ability, split[1].toInt())
        }
        else if (arg.startsWith("--maxTurns")) {
            Constants.NUM_TURNS_PER_SCENARIO = arg.split("=")[1].toInt()
        }
        else if (arg.startsWith("--maxResults")) {
            Constants.SCENARIO_OUTPUT_MAX = arg.split("=")[1].toInt()
        }
        else if (arg.startsWith("-")) {
            when (arg) {
                "-d" -> Globals.debug = true
                "--csv" -> AttackResultFormatter.isCSV = true;
                "-a" -> {
                    val monster = Globals.getMonster(args[i+1])

                    for (turn in args[i+2].split(";")) {
                        val attackList = mutableListOf<Attack>()
                        for (attackName in turn.split(",")) {
                            try {
                                attackList.add (Attack (monster, character!!.getWeapon(attackName)))
                            }
                            catch (e: Exception) {
                                attackList.add (Attack (monster, Globals.getSpell(attackName, character!!.is2014())))
                            }
                        }
                        turns.add(Turn(attackList))
                    }

                    break
                }
                "-z" -> {
                    val monster = Globals.getMonster(args[i+1])
                    val builder = ScenarioBuilder(character!!,monster)
                    builder.showResults(builder.runScenarios (args[i+2].toInt()))
                }
                else -> println("invalid argument: $arg")
            }
        }
        else if (arg.endsWith(".json")) {
            val jsonString = getFileOrURL(arg)
            if (jsonString == null) {
                println("unable to read input: $arg")
            }
            else if (jsonString.contains("School")) {
                spells.addAll(Json.decodeFromString(jsonString))
            }
            else if (jsonString.contains("\"Monsters\"")){
                monsters.addAll(Json.decodeFromString(jsonString))
            }
            else if (jsonString.contains("\"username\"")) {
                character = Json.decodeFromString(jsonString)
            }
        }
        else if (arg.endsWith(".json")){
            println("unknown file type: $arg")
        }
        else if (arg.startsWith("character") || arg.startsWith("https://www.dndbeyond.com/characters")) {
            character = getCharacter(arg)
        }
        else if (arg.startsWith("dump")) {
            Globals.dump(arg, character, turns)
            exitEarly = true
        }
        else if (arg.startsWith("search")) {
            Globals.search(arg)
            exitEarly = true
        }
        else if (arg.startsWith("test:character")) {
            prettyPrintCharacter(character!!)
            exitEarly = true
        }
        else if (arg.startsWith("test:available")) {
            ScenarioBuilder(character!!, Globals.getMonster("Goblin")).testActionsAvailable() // hack
            exitEarly = true
        }
        else if (arg.startsWith("test:file:write")) {
            CmdTest.writeToFile("this is a test", "example.txt")
            exitEarly = true
        }
        else if (arg.startsWith("test:file:read")) {
            val result = CmdTest.readFromFile("example.txt")
            println("read result = $result")
            exitEarly = true
        }
    }

    if (exitEarly) {
    }
    else if (spells.isEmpty()) {
        println("no spell data")
    }
    else if (monsters.isEmpty()) {
        println("no monsters data")
    }
    else if (character == null) {
        println("no character data")
    }
    else if (turns.isNotEmpty()) {
        val scenario = Scenario(character, turns)
        val scenarioResult = ScenarioCalculator(scenario).calculateDPRForAllTurns()
        scenarioResult.output()
    }

    CmdTest.closeHttpClient() // don't forget to do this, otherwise the program may run forever
}
