/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr.turn

import com.vikinghelmet.dnd.dpr.character.Character
import com.vikinghelmet.dnd.dpr.character.inventory.Weapon
import com.vikinghelmet.dnd.dpr.monsters.Monster
import com.vikinghelmet.dnd.dpr.spells.Spell
import com.vikinghelmet.dnd.dpr.util.DiceBlockHelper
import com.vikinghelmet.dnd.dpr.util.Globals
import kotlinx.serialization.json.Json

object TurnCalculator {

    val spells = ArrayList<Spell>()
    val monsters = ArrayList<Monster>()
    val turns = ArrayList<Turn>()
    var character: Character? = null
    var outputFormat = "txt"
    var scenario = ""

    data class RunningSpell (val startTurn: Int, val spell: Spell)
    var runningSpellList = mutableListOf<RunningSpell>()
    fun getRunningSpells(): MutableList<Spell> {
        val result = mutableListOf<Spell>()
        for (running in runningSpellList) result.add(running.spell)
        return result
    }
    fun pruneRunningSpells(turnId: Int) {
        val iterator = runningSpellList.listIterator()
        while (iterator.hasNext()) {
            val running = iterator.next()
            val deltaT = turnId - running.startTurn
            val spell = running.spell
            val duration = spell.getDuration() ?: 0
            if (deltaT >= duration) {
                Globals.debug("spell is complete, remove from running list: "+spell.name)
                iterator.remove()
            }
        }
    }

    fun getPreconditions(turnId: Int, actionCount: Int, turn: Turn, currentSpell: Spell?): Preconditions? {
        if (turnId == 1 && actionCount == 1) return turn.preconditions
        val precondition = Preconditions()

        for (running in runningSpellList) {
            val effect = running.spell.getTargetEffect()

            // extra damage from old spells can be applied independently (does not depend on "currentSpell")
            for (damage in effect.attackerExtraDamageOnHit) {
                if (precondition.bonusDamageDice == null) {
                    precondition.bonusDamageDice = DiceBlockHelper.emptyBlock()
                }
                precondition.bonusDamageDice = precondition.bonusDamageDice!!.add (DiceBlockHelper.getDiceBlock (damage))
            }

            if (currentSpell != null) {
                currentSpell.preProcessEffectsOfOldSpell (running.spell, precondition)
            }
        }
        return precondition
    }

    fun calculateDPRForAllTurns() {
        var turnId = 1
        var scenarioTotalDamage = 0f

        for (turn in turns) {
            var dpr = 0f
            var actionCount = 1
            AttackResultFormatter.header(outputFormat)

            for (attack in turn.attacks) {
                val damage = calculateDPR(turnId, actionCount, turn, attack)
                dpr += damage
                actionCount++
            }

            AttackResultFormatter.footer(outputFormat, scenario, turnId, "TURN TOTAL", dpr)

            pruneRunningSpells(turnId)
            turnId++
            scenarioTotalDamage += dpr
        }

        AttackResultFormatter.footer(outputFormat, scenario, "", "SCENARIO TOTAL", scenarioTotalDamage)
        System.err.println()
    }

    fun calculateDPR(turnId: Int, actionId: Int, turn: Turn, attack: Attack): Float {
        val monster = getMonster(attack.monster)
        if (monster == null) {
            println("monster not found: "+attack.monster)
            return 0f
        }

        val dpr = DamagePerRound(character!!)

        val spell = getSpell(attack.attack)
        attack.preconditions = getPreconditions(turnId, actionId, turn, spell)

        if (spell != null) {
            var totalDamage = 0f
            var effectCount = 1
            for (spellAttack in spell.getSpellAttacks()) {
                val attackResult = if (spellAttack.attackPayload.description == null && spellAttack.damagePayload == null) { // hack
                    dpr.getNoDamageSpellDPR (spell)
                }
                else if (spellAttack.isSavingThrowAttack()) {
                    dpr.getSavingThrowSpellDPR (spellAttack, spell, attack, monster)
                } else {
                    dpr.getMeleeOrRangeDPR (MeleeOrRangeAttack (character!!, spellAttack, null), attack, monster)
                }

                spell.postProcessEffectsOfOldSpells(getRunningSpells(), attackResult)
                attackResult.output( outputFormat, character!!, monster, attack, scenario, turnId, ""+actionId, effectCount, null, spellAttack)

                totalDamage += attackResult.damagePerRound.avg
                effectCount ++
            }
            if (!spell.getTargetEffect().isEmpty()) { // we only track spells with a non-empty effect
                runningSpellList.add(RunningSpell(turnId, spell))
                Globals.debug("adding to running list: "+spell.name)
            }
            return totalDamage
        }

        val weapon = getWeapon(attack.attack)
        if (weapon != null) {
            val meleeOrRangeAttack = MeleeOrRangeAttack(character!!, null, weapon)
            val attackResult = dpr.getMeleeOrRangeDPR (meleeOrRangeAttack, attack, monster)

            attackResult.output(outputFormat, character!!, monster, attack, scenario, turnId,""+actionId,1, weapon,null)
            return attackResult.damagePerRound.avg
        }

        System.err.println()
        System.err.println("spell or weapon not found: "+attack.attack)
        System.err.println()
        System.err.println("character weapons: "+ character!!.getWeaponNames())
        System.err.println()

        return 0f
    }

    fun getMonster(name: String): Monster? {
        if (monsters.isEmpty()) return null

        for (monster in monsters) {
            if (monster.name == name) {
                return monster
            }
        }
        return null
    }

    fun getSpell(name: String?): Spell? {
        if (name == null || spells.isEmpty()) return null

        for (spell in spells) {
            if (spell.name == name) {
                if (!spell.isSameIn2014And2024() && character!!.is2014() != spell.is2014()) {
                    continue
                }

                return spell
            }
        }
        return null
    }

    fun getWeapon(name: String?): Weapon? {
        if (name == null || character == null || character!!.getWeaponList().isEmpty()) return null
        for (weapon in character!!.getWeaponList()) if (weapon.name == name) return weapon
        return null
    }

    fun dump(arg: String) {
        if (!arg.contains(":")) {
            for (item in spells)    println(Json.encodeToString(item))
            for (item in monsters)  println(Json.encodeToString(item))
            for (item in turns)   println(Json.encodeToString(item))
            println(Json.encodeToString(character))
            return
        }

        val dumpType = arg.split(":")[1]
        when (dumpType) {
            "spells" -> {
                for (item in spells)  println(Json.encodeToString(item))
            }
            "monsters" -> {
                for (item in monsters)  println(Json.encodeToString(item))
            }
            "attacks" -> {
                for (item in turns)  println(Json.encodeToString(item))
            }
            "character" -> {
                println(Json.encodeToString(character))
            }
        }
    }

    fun search(arg: String) {
        val searchValue = arg.split(":")[1]
        for (item in spells) if (item.name.contains(searchValue))  println(Json.encodeToString(item))
        for (item in monsters) if (item.name.contains(searchValue))  println(Json.encodeToString(item))
    }

}
