package com.vikinghelmet.dnd.dpr.character.spells

import com.vikinghelmet.dnd.dpr.util.Globals

enum class SpellsChanged2024 {
    // https://rpgbot.net/dnd-2024-5e-transition-guide-and-change-log-everything-thats-different-in-the-new-players-handbook/#spell-changes
    AcidSplash,
    AlterSelf,
    AnimalMessenger,
    AnimalShapes,
    AnimateObjects,
    AntilifeShell,
    ArcaneLock,
    ArmorofAgathys,
    AuraofPurity,
    AuraofVitality,
    BanishingSmite,
    Banishment,
    Barkskin,
    BigbysHand,
    ClenchedFist,
    ForcefulHand,
    GraspingHand,
    InterposingHand,
    BladeWard,
    Bless,
    BlindnessDeafness,
    BrandingSmite,
    CalmEmotions,
    ChillTouch,
    ChromaticOrb,
    CircleofDeath,
    CloudofDaggers,
    ColorSpray,
    Command,
    Compulsion,
    Confusion,
    ConjureAnimals,
    ConjureBarrage,
    ConjureCelestial,
    ConjureElemental,
    ConjureFey,
    ConjureMinorElementals,
    ConjureVolley,
    ConjureWoodlandBeings,
    ContactOtherPlane,
    Contagion,
    Counterspell,
    CreateFoodandWater,
    CureWounds,
    Darkness,
    Darkvision,
    Daylight,
    Demiplane,
    DisguiseSelf,
    DispelEvilandGood,
    DivineFavor,
    DivineWord,
    DominateMonsterDominatePerson,
    DrawmijsInstantSummons,
    Dream,
    Earthquake,
    EnhanceAbility,
    EnsnaringStrike,
    Entangle,
    Enthrall,
    Etherealness,
    EvardsBlackTentacles,
    Eyebite,
    FaerieFire,
    FalseLife,
    FindFamiliar,
    FindSteed,
    Fireball,
    FlameBlade,
    FlameStrike,
    FlamingSphere,
    FleshtoStone,
    Forcecage,
    Foresight,
    Friends,
    GaseousForm,
    GiantInsect,
    Goodberry,
    GraspingVine,
    Grease,
    Guidance,
    HailofThorns,
    Haste,
    HealingWord,
    HolyAura,
    HuntersMark,
    IceStorm,
    Identify,
    InflictWounds,
    Invisibility,
    Jump,
    LegendLore,
    LeomundsTinyHut,
    LesserRestoration,
    LightningArrow,
    LocateCreature,
    MagicJar,
    MagicMissile,
    MagicWeapon,
    MajorImage,
    MassCureWounds,
    MassHealingWord,
    MassSuggestion,
    Maze,
    MindBlank,
    MinorIllusion,
    MirrorImage,
    Mislead,
    Moonbeam,
    MordenkainensFaithfulHound,
    MordenkainensMagnificentMansion,
    MordenkainensSword,
    MoveEarth,
    NystulsMagicAura,
    OttosIrresistibleDance,
    PassWithoutTrace,
    PhantasmalForce,
    PhantasmalKiller,
    PlanarAlly,
    PlaneShift,
    PoisonSpray,
    Polymorph,
    PowerWordHeal,
    PowerWordKill,
    PowerWordStun,
    PrayerofHealing,
    PrismaticSpray,
    PrismaticWall,
    ProduceFlame,
    ProjectImage,
    ProtectionfromPoison,
    RayofEnfeeblement,
    RaiseDead,
    RarysTelepathicBond,
    RayofSickness,
    Regenerate,
    Reincarnate,
    Resistance,
    Resurrection,
    RopeTrick,
    SacredFlame,
    Sanctuary,
    SearingSmite,
    SeeInvisibility,
    Seeming,
    Sending,
    Shapechange,
    Shillelagh,
    ShiningSmite,
    ShockingGrasp,
    SilentImage,
    Simulacrum,
    Sleep,
    SleetStorm,
    Slow,
    SparetheDying,
    SpeakwithAnimals,
    SpeakwithPlants,
    SpiderClimb,
    SpikeGrowth,
    SpiritGuardians,
    SpiritualWeapon,
    StaggeringSmite,
    StinkingCloud,
    Stoneskin,
    StormofVengeance,
    Suggestion,
    SummonAberration,
    SummonConstruct,
    SummonDragon,
    SummonFey,
    SummonUndead,
    Symbol,
    SwiftQuiver,
    TashasHideousLaughter,
    Telekinesis,
    Telepathy,
    Teleport,
    TeleportationCircle,
    Thaumaturgy,
    Tongues,
    TruePolymorph,
    TrueSeeing,
    TrueStrike,
    ViciousMockery,
    Web,
    Weird,
    WindWalk,
    WindWall,
    Wish,
    WitchBolt,
    WordofRecall,
    WrathfulSmite,
    ;

    fun getNameWithWS(): String {
        return when(this) {
            BigbysHand -> "Bigby’s Hand"

            BlindnessDeafness -> "Blindness/Deafness"
            DominateMonsterDominatePerson -> "Dominate Monster / Dominate Person"

            DrawmijsInstantSummons -> "Drawmij’s Instant Summons"
            EvardsBlackTentacles -> "Evard’s Black Tentacles"
            HuntersMark -> "Hunter’s Mark"
            LeomundsTinyHut -> "Leomund’s Tiny Hut"
            MordenkainensFaithfulHound -> "Mordenkainen’s Faithful Hound"
            MordenkainensMagnificentMansion -> "Mordenkainen’s Magnificent Mansion"
            MordenkainensSword -> "Mordenkainen’s Sword"
            NystulsMagicAura -> "Nystul’s Magic Aura"
            OttosIrresistibleDance -> "Otto’s Irresistible Dance"
            RarysTelepathicBond -> "Rary’s Telepathic Bond"
            TashasHideousLaughter -> "Tasha’s Hideous Laughter"

            else -> Globals.addWStoCamelCase(name)
        }
    }
}