/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

import kotlin.test.Test
import kotlin.test.assertNotNull

class DprCmdTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = DprCmd()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
