/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

import com.vikinghelmet.dnd.dpr.character.Character
import com.vikinghelmet.dnd.dpr.character.spells.AlwaysPreparedList
import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import kotlinx.serialization.json.Json

object CmdTest {
    const val characterUrlPrefix = "https://character-service.dndbeyond.com/character/v5"

    var client: HttpClient? = null

    fun getHttpClient(): HttpClient {
        if (client == null) {
            client = HttpClient()
        }
        return client!!
    }

    fun closeHttpClient() {
        if (client != null) client!!.close()
    }

    suspend fun getRequest(url: String): String {
        val response = getHttpClient().get(url)
        return response.bodyAsText() ?: "{}"
    }

    fun getCharacterId(arg: String): String? {
        return if (arg.contains("/")) arg.substringAfterLast("/")
        else if (arg.contains(":")) arg.split(":")[1]
        else if (arg.toIntOrNull() != null) arg
        else null
    }

    suspend fun getRemoteCharacter(id: String): Character? {
        return getRemoteCharacterByUrl(getCharacterApiURL(id))
    }

    fun getAlwaysPreparedSpellList(character: com.vikinghelmet.dnd.dpr.character.Character): AlwaysPreparedList? {
        val campaignId = character.characterData.campaign?.id ?: 0
        val bgid = character.characterData.background?.definition?.id ?: 0
        val subclassId = character.getClassId()
        val url = "$characterUrlPrefix/game-data/always-prepared-spells?campaignId=7230418&sharingSetting=2&classId=19&classLevel=2&backgroundId=7"
        return null
    }

    suspend fun getRemoteCharacterByUrl(url: String): Character? {
        return Json.decodeFromString(getRequest(url))
    }

    fun getCharacterApiURL(id: String): String {
        return "$characterUrlPrefix/character/$id"
    }

}