/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

import com.vikinghelmet.dnd.dpr.character.Character
import io.ktor.client.*
import io.ktor.client.request.*
import io.ktor.client.statement.*
import kotlinx.serialization.json.Json

object CmdTest {
    const val characterUrlPrefix = "https://character-service.dndbeyond.com/character/v5/character/"

    var client: HttpClient? = null

    fun getHttpClient(): HttpClient {
        if (client == null) {
            client = HttpClient()
        }
        return client!!
    }

    fun closeHttpClient() {
        if (client != null) client!!.close()
    }

    suspend fun getRequest(url: String): String {
        val response = getHttpClient().get(url)
        return response.bodyAsText() ?: "{}"
    }

    fun getCharacterId(arg: String): String? {
        return if (arg.contains("/")) arg.substringAfterLast("/")
        else if (arg.contains(":")) arg.split(":")[1]
        else if (arg.toIntOrNull() != null) arg
        else null
    }

    suspend fun getRemoteCharacter(id: String): Character? {
        return getRemoteCharacterByUrl(characterUrlPrefix + id)
    }

    suspend fun getRemoteCharacterByUrl(url: String): Character? {
        return Json.decodeFromString(getRequest(url))
    }
}