/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

const val settingsPath = ".dpr/settings.json"
const val characterBaselineDir = ".dpr/character/baseline"
const val characterEditableDir = ".dpr/character/editable"

const val exportDir = ".dpr/export"

