/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

import com.vikinghelmet.dnd.dpr.character.Character
import com.vikinghelmet.dnd.dpr.modified.EditableCharacter
import com.vikinghelmet.dnd.dpr.modified.EditableFields
import com.vikinghelmet.dnd.dpr.util.DprSettings
import kotlinx.io.*
import kotlinx.io.files.Path
import kotlinx.io.files.SystemFileSystem
import kotlinx.serialization.json.Json

const val settingsPath = ".dpr/settings.json"
const val characterBaselineDir = ".dpr/character/baseline"
const val characterEditableDir = ".dpr/character/editable"

class DprFiles(val appDataDir: String)
{
    fun init() {
        SystemFileSystem.createDirectories(Path(appDataDir+"/"+characterBaselineDir))
        SystemFileSystem.createDirectories(Path(appDataDir+"/"+characterEditableDir))
    }

    fun deleteAll() {
        for (file in list(characterBaselineDir) + list(characterEditableDir)) {
            SystemFileSystem.delete(Path(file))
        }
        saveSettings(DprSettings())
    }

    fun getSettings(): DprSettings {
        val settings: DprSettings = Json.decodeFromString(read(settingsPath) ?: "{}")
        println("settings: $settings")
        return settings
    }

    fun saveSettings(settings: DprSettings) {
        val settingsString = Json.encodeToString(settings)
        write(settingsString, settingsPath)
    }

    fun saveCharacter(json: String, characterId: String) {
        write(json, characterBaselineDir+"/"+characterId)
    }

    fun saveEditableCharacter(editableFields: EditableFields) {
        // TODO: for filename, use localId instead of name ???
        write(Json.encodeToString(editableFields), characterEditableDir+"/"+editableFields.name)
    }

    fun deleteEditableCharacter(name: String) {
        delete(characterEditableDir+"/"+name)
    }

    fun getEditableFields(name: String): EditableFields? {
        if (name.isEmpty()) return null
        val json = read(characterEditableDir+"/" + name) ?: return null
        return Json.decodeFromString(json)
        /*
        val result: EditableFields = Json.decodeFromString(json)
        result.name = name
        return result */
    }

    fun getEditableCharacter(name: String): EditableCharacter? {
        //println("getEditableCharacter, settings name = $name")
        val editableFields = getEditableFields(name) ?: return null
        //println("getEditableCharacter, editableFields = $editableFields")
        if (editableFields.remoteId == 0) {
            println("getEditableCharacter, remoteId=0")
            return null
        }
        val baseline = getCharacter(editableFields.remoteId.toString()) ?: return null
        //println("getEditableCharacter, baseline = $baseline")
        return EditableCharacter(baseline, editableFields)
    }

    fun getCharacter(characterId: String): Character? {
        val json = read(characterBaselineDir+"/" + characterId)
        return if (json !=null) Json.decodeFromString(json) else null
    }

    fun getEditableCharacterList(): List<String> {
        return list(characterEditableDir).map { p -> p.substringAfterLast('/') }
    }

    fun list(subdir: String): List<String> {
        val pathList = SystemFileSystem.list(Path(appDataDir+"/"+subdir))
        return pathList.map { p -> p.toString() }
    }

    fun write(data: String, filename: String) {
        try {
            SystemFileSystem.sink(Path(appDataDir+"/"+filename)).buffered().use { sink: Sink ->
                sink.writeString(data)
                sink.flush()
            }
            println("Data written to $filename")
        } catch (e: Exception) {
            println("Error writing file: $e")
        }
    }

    fun read(filename: String): String? {
        try {
            SystemFileSystem.source(Path(appDataDir+"/"+filename)).buffered().use { source: Source ->
                val content = source.readString()
                return content
            }
        } catch (e: Exception) {
            e.printStackTrace()
            println("Error reading file: $e")
            return null
            //return "{}" // TODO: better default ?
        }
    }

    fun delete(filename: String) {
        try {
            SystemFileSystem.delete(Path(appDataDir+"/"+filename))
        } catch (e: Exception) {
            e.printStackTrace()
            println("Error deleting file: $e")
        }
    }

}