/*
 * This source file was generated by the Gradle 'init' task
 */
package com.vikinghelmet.dnd.dpr

import com.vikinghelmet.dnd.dpr.character.Character
import com.vikinghelmet.dnd.dpr.modified.CharacterOverrides
import com.vikinghelmet.dnd.dpr.util.DprSettings
import kotlinx.io.*
import kotlinx.io.files.Path
import kotlinx.io.files.SystemFileSystem
import kotlinx.serialization.json.Json

const val settingsPath = ".dpr/settings.json"
const val characterBaselineDir = ".dpr/character/baseline"
const val characterLevelupDir = ".dpr/character/levelup"

class DprFiles(val appDataDir: String)
{
    fun init() {
        SystemFileSystem.createDirectories(Path(appDataDir+"/"+characterBaselineDir))
        SystemFileSystem.createDirectories(Path(appDataDir+"/"+characterLevelupDir))
    }

    fun getSettings(): DprSettings {
        val settings: DprSettings = Json.decodeFromString(read(settingsPath) ?: "{}")
        println("settings: $settings")
        return settings
    }

    fun saveSettings(settings: DprSettings) {
        val settingsString = Json.encodeToString(settings)
        write(settingsString, settingsPath)
    }

    fun saveCharacter(character: Character, characterId: String) {
        write(Json.encodeToString(character), characterBaselineDir+"/"+characterId)
    }

    fun saveModifiedCharacter(characterOverrides: CharacterOverrides) {
        // TODO: for filename, use localId instead of name ???
        write(Json.encodeToString(characterOverrides), characterLevelupDir+"/"+characterOverrides.name+".json")
    }

    fun getModifiedCharacter(name: String): CharacterOverrides? {
        val json = read(characterLevelupDir+"/" + name+".json")
        return if (json !=null) Json.decodeFromString(json) else null
    }

    fun getCharacter(characterId: String): Character? {
        val json = read(characterBaselineDir+"/" + characterId)
        return if (json !=null) Json.decodeFromString(json) else null
    }

    fun getCharacterList(): List<String> {
        return list(characterBaselineDir).map { p -> p.substringAfterLast('/') }
    }

    fun list(subdir: String): List<String> {
        val pathList = SystemFileSystem.list(Path(appDataDir+"/"+subdir))
        return pathList.map { p -> p.toString() }
    }

    fun write(data: String, filename: String) {
        try {
            SystemFileSystem.sink(Path(appDataDir+"/"+filename)).buffered().use { sink: Sink ->
                sink.writeString(data)
                sink.flush()
            }
            println("Data written to $filename")
        } catch (e: Exception) {
            println("Error writing file: $e")
        }
    }

    fun read(filename: String): String? {
        try {
            SystemFileSystem.source(Path(appDataDir+"/"+filename)).buffered().use { source: Source ->
                val content = source.readString()
                return content
            }
        } catch (e: Exception) {
            println("Error reading file: $e")
            return null
            //return "{}" // TODO: better default ?
        }
    }

}